apiVersion: v1
kind: Service
metadata:
    name: "rkorddev-2d42"
    labels:
        app: "rkorddev-2d42"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "rkorddev-2d42"